### ISSUE TITLE
Support Multiple Templates for Different Types of Notes

### ISSUE THREAD

**Issue by theianjones** [aengusmcmillin/gatsby-theme-brain#18]
### Brief Abstract
I would like to be able to render brain notes differently based on the type of note that I am taking.
Some types of notes would include: books, code snippets, sketchnotes, etc. 

### Proposed Implementation

I think adding a `templateType` or `noteType` on the Brian node schema and render whatever the node type is into its corresponding template. We could set the default as `brain` and the default template would be `brain.js` so that we wouldn't break anyones builds.

We could add `template` to the markdown frontmatter as a way of determining which template the file should be rendered as.

We will want to check that the `templateType` is found inside of the templates folder, this will likely require shadowing from the user. 

If the user has not defined a template for their custom `templateType` we could print a warning that a template was not found and render the brain template as a default.

**Comment by leerob** [comment]
I've been working on a similar version of this with Next.js. You might be able to pull inspiration from [next-mdx-enhanced](https://github.com/hashicorp/next-mdx-enhanced/), which has a concept of "layouts".

**Comment by aengusmcmillin** [comment]
I like this idea!

I'm thinking probably the best thing would be to include a new field in pluginOptions containing key/value pairs for the noteType and the template file. Will keep the existing field for the people that have already overridden it, but the new field will provide extra options that will be used if a noteType is declared in the frontmatter. 

Can try and get this implemented in the next day or two.
