### ISSUE TITLE
Access childMdx frontmatter

### ISSUE THREAD

**Issue by theianjones** [aengusmcmillin/gatsby-theme-brain#27]
@MaggieAppleton and I are [integrating gatsby-theme-brain into her site (github link)](https://github.com/MaggieAppleton/maggieappleton.com/tree/bidirectionals). Maggie currently uses frontmatter to annotate her posts with metadata:

https://github.com/MaggieAppleton/maggieappleton.com/blob/d0a805dedaae58a5282a3b5c9d8a0e05bef9bb83/src/templates/noteTemplate.js#L127-L132

We want to access these same fields through a brain note object. We thought that these fields should live here:

```
brainNote(slug: { eq: $slug }) {
  childMdx {
        body
        frontmatter {
          title
          date(formatString: "MMMM DD, YYYY")
          slug
          topics
        }
      }
}
```

But they are turning up null. 

How can we access frontmatter of the mdx post?

**Comment by aengusmcmillin** [comment]
I actually had fixed this when adding RSS support, I just never got around to pushing a new version. Just published a new build. You should be able to update to 1.0.12 and this should work.

**Comment by theianjones** [comment]
awesome, thanks!

**Comment by MaggieAppleton** [comment]
Whoo! It's working now. Thank you!
