### ISSUE TITLE
Backlink preview: add support for rendering context around backlinks

### ISSUE THREAD

**Issue by mxstbr** [aengusmcmillin/gatsby-theme-brain#3]
I know this is already on the roadmap (according to [this comment in the code](https://github.com/aengusmcmillin/gatsby-theme-brain/blob/b8fe0007943b6c6c2e66fd3991076b2763d8559e/src/source-nodes.js#L89-L90)), I just wanted to point out that for https://notes.andymatuschak.org Andy built https://github.com/andymatuschak/note-link-janitor, which does this exact extraction.

While the module directly is probably not usable for this purpose, we should be able to take some inspiration (_cough_) from the implementation!

**Comment by aengusmcmillin** [comment]
Ah nice, didn't know he had open sourced that. Yeah I will look through and see how he does it and figure out what I can port to Gatsby.

**Comment by aengusmcmillin** [comment]
Let me know how you feel about the implementation of this :)

It is a pretty minimal preview still, but it works!
