### ISSUE TITLE
Support org-mode files

### ISSUE THREAD

**Issue by bphenriques** [aengusmcmillin/gatsby-theme-brain#36]
Hello! I really like this theme and [its cousin andy](https://github.com/aravindballa/gatsby-theme-andy). Thank you for making these available.

While I was exploring this theme (and gatsby) with `org-mode` files (through org-roam) I encountered the following:
```
"gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:

unknown: Unexpected token (13:0)

  11 |   )
  12 | }
> 13 | #+end_src
     | ^
  14 | content/hello.org: unknown: Unexpected token (13:0)

  11 |   )
  12 | }
> 13 | #+end_src
```

I believe this is known limitation as the theme only support markdown files. I attempted to use [https://orga.js.org/docs/generate-static-website-with-gatsby](https://orga.js.org/docs/generate-static-website-with-gatsby), however that does not yield the desired results as the notes are not pre-processed by the theme (I believe [here](https://github.com/aengusmcmillin/gatsby-theme-brain/blob/ccc3b237fc299ae2718fada09901825a0efa51b6/src/source-nodes.js#L516)).

Is this use-case known to you and do you know if this is possible?

**Comment by aengusmcmillin** [comment]
I think there might be a way to do this, but it would require some custom modification that I'm not positive should live in the main plugin.

Likely the way to do this would be to adjust the notesFileExtensions parameter to include org mode files, and add handling for org mode files to set the output type to be OrgFile nodes, and hopefully that would trigger orga.

The problem is that there is other logic around the plugin that relies on markdown parsing. So it might make more sense to fork this or extend it and override specific necessary components.

**Comment by bphenriques** [comment]
Thank you for the feedback 👍  

> Likely the way to do this would be to adjust the notesFileExtensions parameter to include org mode files, and add handling for org mode files to set the output type to be OrgFile nodes, and hopefully that would trigger orga.

👍 

> that I'm not positive should live in the main plugin (...) So it might make more sense to fork this or extend it and override specific necessary components.

So if I understand correctly: Gatsby should support `org-mode` natively as yet another data-source and then it would be "just" using the right renderer depending on the extension of the file?

I do not want to re-invent the wheel so I am exploring how to leverage existing tools to convert from `org` to `md` to feed Gatsby. As far as I found, and as reference for anyone interested in this:
* `ox-hugo` works mostly well but the export is tailored to `hugo` (no surprise). The links do not work as they are exported as (if I recall) `[file]({ relref 'file.md' })`. 
* The existing Emacs exporter to `md`  requires additional boilerplate, but even then the links in the `org` markdown counterpart include the `.md` extension which break the linking in this theme. It may be possible to remove the extension but paused that thread.

**Comment by bphenriques** [comment]
Closing as I am no longer requiring this, do re-open if you believe it is important for this project. Thank you!
