### ISSUE TITLE
Allow custom component imports into MDX notes

### ISSUE THREAD

**Issue by MaggieAppleton** [aengusmcmillin/gatsby-theme-brain#37]
A lot of my notes have custom React component imports at the top.

These components are usually kept in the same folder as the note (but given the current top-folder-level system for gatsby-theme-brain, I'll likely to move them into a single `/note-components` location).

When I try to run them with gatsby-theme-brain I get a caching error. Eg.

```
Generating development JavaScript bundle failed

Can't resolve './Tools.js' in '/Users/maggie/Documents/GitHub/maggieappleton.com/.cache/caches/gatsby-plugin-mdx/mdx-scopes-dir'

File: .cache/caches/gatsby-plugin-mdx/mdx-scopes-dir/87e93eac8b8fe4b4034bd8543157f22a.js
```

Cleaned the cache 99 times and it has yet to work 😅

Popped it onto a branch here: https://github.com/MaggieAppleton/maggieappleton.com/tree/bidirectional-custom-components-error

The note I was testing it out with is `apps.mdx`, and trying to import components from `Tools.js`
- https://github.com/MaggieAppleton/maggieappleton.com/blob/bidirectional-custom-components-error/content/notes/apps.mdx
- https://github.com/MaggieAppleton/maggieappleton.com/blob/bidirectional-custom-components-error/content/notes/Tools.js

All the other component-less notes work fine. Seems to only be an issue with component imports.

**Comment by aengusmcmillin** [comment]
Spent some time looking into this. There might be something that I can get working, although looking at https://github.com/ChristopherBiscardi/gatsby-mdx/issues/176, I'm not certain if relative directory js files are supported.

I was able to get this working with Chris's workaround though. In a test site I created a Tools.js file in the src/ directory, pasted this code into gatsby-node.js

```
const path = require("path");

exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      modules: [path.resolve(__dirname, "src"), "node_modules"],
    },
  });
};
```

and then I was able to do 
```
import { Tools, Hardware } from 'Tools'

<Tools />
<Hardware />
```

And the components rendered.

Was this sort of relative importing of components working for you before switching to gatsby-theme-brain? If so this must be possible and I will keep digging, but at least that is an option to get this working for you again.

**Comment by MaggieAppleton** [comment]
Ah it's okay - wasn't sure if it was an easy fix, but not a big deal - there are definitely workarounds.

That `onCreateWebpackConfig` function is what renders any custom components I have stored under the `src/` folder - eg. I have a lot of components in `src/components/` that apply to all my MDX files across types.

But before I could also add single components in the `content/` directory for each note post.

Eg. `content/notes/tools/` would have `index.mdx` with the post and the `Tools.js` component inside. Helped to keep components and MDX together if the component was a limited use case (eg. Tools.js isn't used in any other note) but definitely not a requirement!

Thanks for giving it a look.
I think it's just related to gatsby-brain querying a flat folder of .mdx files rather than nested folders of notes. Which honestly makes a lot more sense for the general use case - I'm always the weirdo edge case here lol
